version: '3'

services:
  db:
    image: mariadb
    # image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PWD}
    env_file:
      - ./db/db.env

  app:  
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - ./db/db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    ports:
      - {MY_PUBLIC_IP_ADDRESS}:80:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud:
